package com.chiang.springcloud.dao;

import java.util.List;

import com.chiang.springcloud.bean.User;

public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuser
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cuser
     *
     * @mbg.generated Wed Oct 02 20:42:31 CST 2019
     */
    int insertSelective(User record);
    public List<User> findAll();
}